#!/usr/bin/env python3
r"""Render compact LaTeX robustness tables from generated CSV files.

Run after

    python scripts/run_repeated_seed_study.py ...
    python scripts/run_shot_noise_study.py ...

The output file can be inserted into report/project2_report.tex with

    \input{robustness_tables}

near the end of the Results/discussion section or in the Reliability and
limitations subsection.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-dir", default="results")
    parser.add_argument("--output", default="report/robustness_tables.tex")
    return parser.parse_args()


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"Missing {path}. Run the corresponding experiment first.")
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def fmt_pm(mean: str | float, std: str | float, digits: int = 3) -> str:
    return f"{float(mean):.{digits}f} $\\pm$ {float(std):.{digits}f}"


def short_model_name(name: str) -> str:
    return name.replace("_", "\\_").replace("/", "/")


def repeated_seed_table(rows: list[dict[str, Any]]) -> str:
    body = []
    for row in rows:
        body.append(
            "{} & {} & {} \\\\".format(
                short_model_name(str(row["model"])),
                fmt_pm(row["test_accuracy_mean"], row["test_accuracy_std"]),
                fmt_pm(row["test_loss_mean"], row["test_loss_std"]),
            )
        )
    return r"""
\begin{center}
\captionof{table}{Repeated-seed Iris robustness study. Values are mean $\pm$ standard deviation over several train/test splits and initializations.}
\label{tab:repeated-seed}
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}lcc@{}}
\toprule
Model & test acc. & test loss \\
\midrule
""" + "\n".join(body) + r"""
\bottomrule
\end{tabular}
\end{center}
"""


def shot_noise_table(rows: list[dict[str, Any]]) -> str:
    wanted_models = ["h_rz/simple", "ry/simple", "ry_rz/strong"]
    body = []
    for model in wanted_models:
        for row in rows:
            if row["model"] != model:
                continue
            shots = row["shots"]
            body.append(
                "{} & {} & {} & {} \\\\".format(
                    short_model_name(model),
                    shots,
                    fmt_pm(row["test_accuracy_mean"], row["test_accuracy_std"]),
                    fmt_pm(row["test_loss_mean"], row["test_loss_std"]),
                )
            )
    return r"""
\begin{center}
\captionof{table}{Finite-shot measurement study for Iris. Training uses exact probabilities; inference is repeated with sampled measurements. The exact row is the infinite-shot reference.}
\label{tab:shot-noise}
\setlength{\tabcolsep}{2.5pt}
\begin{tabular}{@{}llcc@{}}
\toprule
Model & shots & test acc. & test loss \\
\midrule
""" + "\n".join(body) + r"""
\bottomrule
\end{tabular}
\end{center}
"""


def interpretation_text() -> str:
    return r"""
The repeated-seed study in Table~\ref{tab:repeated-seed} addresses the main statistical limitation of the single-split results.  The table reports mean and standard deviation over several data splits and parameter initializations, so differences between circuits should be interpreted through both the average performance and the observed variation.  The finite-shot study in Table~\ref{tab:shot-noise} addresses the measurement part of the project.  It keeps the deterministic state-vector training as the clean reference calculation, but replaces the final test probabilities by sampled measurement estimates.  As expected, the exact row gives the most stable probabilities, while smaller shot counts introduce additional variation in accuracy and cross-entropy.
"""


def main() -> None:
    args = parse_args()
    results_dir = Path(args.results_dir)
    repeated_rows = read_csv(results_dir / "iris_repeated_seed_summary.csv")
    shot_rows = read_csv(results_dir / "iris_shot_noise_study.csv")

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    text = (
        "% Automatically generated by scripts/render_robustness_latex_tables.py\n"
        + repeated_seed_table(repeated_rows)
        + "\n"
        + shot_noise_table(shot_rows)
        + "\n"
        + interpretation_text()
    )
    out.write_text(text, encoding="utf-8")
    print(f"Wrote {out}")
    print("Insert this line in report/project2_report.tex:")
    print(r"    \input{robustness_tables}")


if __name__ == "__main__":
    main()
